'use client';
import '../globals.css';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeProvider from '@/common/theme';
import { Providers } from '@/store/provider';
import Header from '@/components/organisms/header';
import { notFound, usePathname } from 'next/navigation';
import { NextIntlClientProvider, useLocale } from 'next-intl';
import useMessage from '@/hooks/useMessage';
import Box from '@/components/atoms/box';
import Audio from '@/components/atoms/audio';
import AuthProvider from '@/utility/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Rent Babe',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children, params }: { children: React.ReactNode; params: any }) {
  const locale = useLocale();
  if (params.locale !== locale) {
    notFound();
  }
  const pathName = usePathname();

  const messages = useMessage();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            <AuthProvider pathName={pathName}>
              <ThemeProvider>
                <Audio />
                {!pathName.includes('login') && !pathName?.includes('profile') && <Header />}
                <Box className={!pathName.includes('login') && !pathName?.includes('profile') ? 'children' : ''}>
                  {children}
                </Box>
              </ThemeProvider>
            </AuthProvider>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
